### ISSUE TITLE
Failure in using RiskAdjustedLinearization

### ISSUE THREAD

**Issue by dypisgood** [chenwilliam77/RiskAdjustedLinearizations.jl#36]
I guess the problem is 
"DiffCach" is missing in the package "DiffEqBase"

Could you please look into this case?
Thanks!

best,
dypisgood

**Comment by chenwilliam77** [comment]
Try pulling from `main` now. It should work now. I'll release the new version in the next couple days.

**Comment by dypisgood** [comment]
Thank you so much!
